import Head from "next/head";
import styles from "../styles/Home.module.css";
import "../firebase/client";
import { getDatabase, ref } from "firebase/database";
import { useList } from "react-firebase-hooks/database";

import Card from "https://framer.com/m/Card-4sci.js@8jR9xBqvFYKTrom9ZS9C";

export default function Home() {
  const db = getDatabase();
  const roomRef = ref(db, "room/voorkamer/current");

  const [snapshots, loading, error] = useList(roomRef);

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Air Quality</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welkom in de
            <br />
            Pixelpillow HQ
          </h1>

          {error && <strong>Error: {error}</strong>}
          {!loading && snapshots && (
            <Card
              roomName="Voorkamer 2"
              backgroundColor="rgba(114, 37, 80, 1)"
              co2={snapshots[0].val()}
              humidity={snapshots[2].val()}
              temperature={snapshots[3].val()}
            />
          )}
        </main>
      </div>
    </>
  );
}
